---
- name: enable usb0 in interfaces
  become: yes
  blockinfile:
      path: /etc/network/interfaces
      marker: "####<------- ANSIBLE MARKER BLOCK ------->####"
      block: |
          allow-hotplug usb0
          iface usb0 inet static
          address 192.168.42.42
          netmask 255.255.255.0
          network 192.168.42.0
          gateway 192.168.42.129
          broadcast 192.168.42.255
- name: setup dhcpcd
  become: yes
  blockinfile:
      path: /etc/dhcpcd.conf
      marker: "####<------- ANSIBLE MARKER BLOCK ------->####"
      block: |
          interface usb0
          static ip_address=192.168.42.42/24
          static routers=192.168.42.1
          static domain_name_servers=192.168.42.1
